#!usr/bin/env bash

# Base packages install on all Systems
BASE=(
  base
  base-devel
  bat
  btop
  curl
  eza
  fastfetch
  fzf
  gum
  git
  github-cli
  herdr
  htop
  linux-firmware
  lm-sensors
  man-db
  man-pages
  shellcheck
  starship
  stow
  tealdeer
  tmux
  unzip
  vim
  wget
  yazi
  zip
  zoxide
)

HYPR=(
  awww
  auto-cpufreq
  cliphist
  ghostty
  google-chrome
  grim
  hyperland
  hyprpolkitagent
  networkmanager
  nm-connection-editor
  obsidian
  quickshell
  rofi
  slurp
  thunar
  virt-manager
  vivaldi
  waybar
  waypaper
  wdisplays
  wl-clipboard
  wl-clip-persist
  xdg-desktop-portal-gnome
  xdg-desktop-portal-gtk
  xdg-desktop-portal-hyprland
  yazi
  zen-browser
)

# Niri Window Manager
# scrollable-tiling Wayland compositor and related tools
NIRI=(
  auto-cpufreq
  awww
  cava
  cliphist
  dms-shell-bin
  grim
  gtk3
  gtk4
  ghostty
  google-chrome
  imv
  iwd
  iwgtk
  matugen
  networkmanager
  niri
  noctalia-shell
  obsidian
  obs-studio
  power-profiles-daemon
  qt6-multimedia-ffmpeg
  qt5ct
  qt6ct
  quickshell
  rofi
  satty
  slurp
  thunar
  virt-manager
  vivaldi
  waybar
  waypaper
  wl-clip-persist
  wl-clipboard
  xwayland-satellite
  xdg-desktop-portal-gnome
  xdg-desktop-portal-gtk
  kanshi
  wdisplays
)

# Qtile x11 Widow Manager
QTILE=(
  qtile
  xorg
  xorg-xrandr
  arandr
  networkmanger
  xdg-desktop-portal
  python
  python3
  vivaldi
  google-chrome
  rofi
  ghostty
  alacritty
  thunar
  cliphist
  obsidian
  power-profiles-daemon
  grim
  slurp
  feh
  waypaper
  neovim
  vim
  sddm
)

# Fonts
# FONTS=(
#   ttf-jetbrains-mono-nerd
#   ttf-font-awesome
#   ttf-roboto
#   ttf-font-awesome
#   ttf-cascadia-mono-nerd
# )

DEV=(
  cargo
  code
  clang
  cmake
  curl
  docker
  docker-compose
  gtk3
  git
  portainer
  ninja
  tmux
  unzip
  xz
  zed
  zip
)

CLI_TOOLS=(
  cmatrix-bin
  figlet
  lastpass-cli
  lolcat
)
