hl.on("hyprland.start", function ()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("qs -p ~/.config/quickshell")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("wl-clip-persist --clipboard regular")
  hl.exec_cmd("/usr/lib/xdg-desktop-portal")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
end)
