
# System Utilities
SYSTEM_UTILS=(
 htop
 btop
 stow
 eza
 fastfetch
 zip
 unzip
 wget
 curl
 fzf
 kitty
 ghostty
 alacritty
 git
 bat
 neovim
 kate
 dolphin
 thunar
 google-chrome-canary
 obsidian
 gwenview
 flatpak
 libreoffice-still
 cliphist
 wl-clipboard
 rofi
 power-profiles-daemon
 light
 waybar
)

# DEV
DEV=(
 python
 python3
 python-pip
 python-gobject
 python3-gobject
 python-screeninfo
)

# Fonts
FONTS=(
 ttf-jetbrains-mono-nerd
 ttf-font-awesome
 ttf-roboto
 noto-fonts
 noto-fonts-emoji
)

# Media
MEDIA=(
 flameshot
 gimp
 vlc
 pipwire
 lib32-pipwire
 pipewire-pulse
 pavucontrol
 pwvucontrol
 swww
 waypaper
 matugen
 wallust
 #feh
)

# Network
NETWORK=(
 networkmanager
 nm-connection-editor
 network-manager-applet
 iwd
 iwgtk
)

# Services
SERVICES=(
 NetworkManager
)
