
# System Utilities
SYSTEM_UTILS=(
 htop
 btop
 stow
 eza
 fastfetch
 zip
 unzip
 wget
 curl
 fzf
 kitty
 ghostty
 git
 bat
 neovim
 networkmanager
 nm-cnnection-editor
 network-manager-applet
 iwd
 iwgtk
)

# Fonts
FONTS=(
 ttf-jetbrains-mono-nerd
 ttf-font-awesome
 ttf-roboto
 noto-fonts
 noto-fonts-emoji
)

# Media
MEDIA=(
 flameshot
 gimp
 vlc
)

# Services
SERVICES=(
 NetworkManager
)
