#!/usr/bin/env bash

rm -rf ~/.config/zsh/plugins


mkdir -p ~/.config/zsh/plugins/

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/plugins/zsh-syntax-highlighting/
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh/plugins/zsh-autosuggestions/
git clone https://github.com/MichaelAquilina/zsh-you-should-use.git ~/.config/zsh/plugins/zsh-you-should-use/
git clone https://github.com/zsh-users/zsh-history-substring-search.git ~/.config/zsh/plugins/zsh-history-substring-search/
git clone https://github.com/sindresorhus/pure.git ~/.config/zsh/plugins/pure/

sudo pacman -S --needed --noconfirm zsh
hash -r
chsh -s $(which zsh)

cd ~/.hyprdots/
stow zsh
